import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { increment, decrement, incrementByAmount } from '../redux/slices/counterSlice'
import { useSelector, useDispatch } from 'react-redux'

const Home: NextPage = () => {
    const dispatch = useDispatch()
    const val = useSelector((state: any) => state.counter.value)

    return (
    <div className={styles.container}>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} onClick={() => dispatch(increment())}>
          Counter: {val}
        </h1>

      </main>
    </div>
  )
}

export default Home
